controllers/FormationrouteController.php
<?php
namespace app\controllers;

use app\models\Postcenters;
use app\models\Centerspost;
use app\models\Distancesmatrix;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\helpers\BaseFileHelper;

//use app\models\Formation;
class FormationrouteController extends Controller
{
    public function actions()
    {
        return [
            'error' =>[
                'class' =>'yii\web\ErrorAction',
            ],
        ];
    }
    
    public function actionChoose()
    {

        if(Yii::$app->user->isGuest)
            return $this->goHome();

        $postcenters = Postcenters::find()->all();
        $postoffices = [];
        foreach ($postcenters as $post)
        {
            $postoffices[] = [
                'idcenter' => $post->idcenter,
                'nameoffices' => $post->nameoffices
            ];
        }
        return $this->render('choose',['postoffices'=>$postoffices]);
    }
    public function actionCreate()
    {
        if(Yii::$app->user->isGuest)
            return $this->goHome();

        $postoffices = [];
        $request = Yii::$app->request;
        $optradio = explode('|',$request->post('optradio'));
        $postoffices['nameoffices'] = $optradio[0];
        $postoffices['id'] = $optradio[1];
        $postoffices['dataroute'] = $request->post('dataroute');

        $postcenters = Centerspost::find()->where(['id_center' =>$postoffices['id']])->all();

        return $this->render('create',['postcenters'=>$postcenters, 'postoffices' => $postoffices]);
    }
    public function actionCreatexsel()
    {
        if(Yii::$app->request->isAjax)
        {
            if(Yii::$app->request->post('routeAll'))
            {
                $routeAll = Yii::$app->request->post('routeAll');
                $inputFileName = './patternxsl/pattern.xlsx';
                $objPHPExcel = \PHPExcel_IOFactory::load($inputFileName);
                $arrRoute = [];
                for($i = 0, $len = count($routeAll); $i<$len; $i++)
                {
                    $arrDataBD = [];
                    $timeLuganskCOPP = null;
                    foreach ($routeAll[$i] as $key => $route)
                    {
                        if($key == 'typeStransport')
                        {
                            $startFinish = explode('|', $route);
                            $arrDataBD['typeStransportStart'] = $startFinish[0];
                            $arrDataBD['typeStransportFinish'] = $startFinish[1];
                            //echo $arrDataBD['typeStransportStart']."---".$arrDataBD['typeStransportFinish']."<br />";
                        }
                        if($key == 'date'){
                            $arrDataBD['date'] = $route;
                        }
                        if($key == 'timeDeparture')
                        {
                            $arrDataBD['timeStart'] =  $route;
                            //echo $arrDataBD['timeStart']."<br />";
                        }
                        if($key == 'timeDurationBreak')
                        {
                            $arrDataBD['timebreak'] =  $route;
                            //echo $arrDataBD['timebreak']."<br />";
                        }
                        /*  if($key == 'timeSharing')
                        {
                            $arrDataBD['timechange'] =  $route;
                            //echo $arrDataBD['timechange']."<br />";
                        }*/
                        if($key == 'placeBreakIdPochta')
                        {
                            $arrDataBD['idbreak'] =  $route;
                           // echo $arrDataBD['idbreak']."<br />";
                        }
                        if($key == 'routeName')
                        {
                            $arrDataBD['routeName'] =  $route;
                           // echo $arrDataBD['routeName']."<br />";
                        }
                        if($key == 'settlingTime')
                        {
                            $arrDataBD['settlingTime'] =  $route;
                        }
                        if($key == 'arrPochta')
                        {
                            for($k = 0, $ln = count($route) - 1; $k<$ln; $k++)
                            {
                                if($k==0) 
                                    $timeLuganskCOPP = $route[$k]['timeSharingLocal'];
                                $j=$k+1;
                                $idcenter = $route[$k]['idcenter'];
                                $idpochtastart = $route[$k]['idpochta'];
                                $idpochtaConststart =  $idpochtastart;
                                $idpochtafinish = $route[$j]['idpochta'];
                                $idpochtaConstfinish = $idpochtafinish;
                                //TODO
                                //для первомайска id_center = 2
                                // если $idpochtastart = 15 заменяем на 1
                                // если $idpochtafinish = 14 заменяем на 4
                                if($route[$k]['idcenter'] == 2)
                                {
                                    if($idpochtastart == 15)
                                        $idpochtastart = 1;
                                    if($idpochtastart == 14)
                                        $idpochtastart = 4;
                                    if($idpochtafinish == 15)
                                        $idpochtafinish = 1;
                                    if($idpochtafinish == 14)
                                        $idpochtafinish = 4;
                                }
                                $sql = "SELECT distance FROM distancesmatrix WHERE `id_center`='$idcenter' AND `id_centerspost_start`='$idpochtastart' AND `id_centerspost_finish`='$idpochtafinish' OR `id_centerspost_start`='$idpochtafinish' AND `id_centerspost_finish`='$idpochtastart'";
                                $distance = Distancesmatrix::findBySql($sql)->asArray()->one();
                                // 40 км/ч = 11 м/c
                                $timeWay = ($distance['distance']*1000)/11;
                                $arrDataBD[] = array('idpochta' =>$route[$j]['idpochta'],'timeSharingLocal' =>$route[$j]['timeSharingLocal'], 'namepochtastart'=>$route[$k]['name'],'namepochta'=>$route[$j]['name'],'timeWay' => $this->secondToHMS($timeWay),'distance' => $distance['distance'],'idpochtaConststart'=>$idpochtaConststart,'idpochtaConstfinish'=>$idpochtaConstfinish);
                                //var_dump($arrDataBD);
                            }
                        }

                    }
                    //start excel
                    //echo "start exsel";
                    //start line in excel file
                    $numberStartLine = 19;
                    $objPHPExcel->setActiveSheetIndex(0);
                    $n = 0;
                    $start = 0;
                    $startFormatExcelFile = true;
                    $endTime = 0;
                    $flayWay = true;
                    $total = array('distanse' => 0,'time' => 0);
                    end($arrDataBD);
                    $last = key($arrDataBD);
                    foreach($arrDataBD as $key => $value)
                    {
                        if($startFormatExcelFile)
                        {
                            //$text = $objPHPExcel->getActiveSheet()->getCell('C8')->getValue();
                            $numberMarchrut = $i+1;
                            $text ="движения автотранспорта по маршруту  №"."$numberMarchrut ".$arrDataBD['routeName'];
                            $objPHPExcel->getActiveSheet()->setCellValue('C8', $text);
                            $timeData = strtotime($arrDataBD['date']);
                            $timeData = date("d-m-Y",$timeData);
                            $objPHPExcel->getActiveSheet()->setCellValue('C9', $timeData." г.");
                            $objPHPExcel->getActiveSheet()->setCellValue('E17', $arrDataBD['timeStart']);
                            $objPHPExcel->getActiveSheet()->setCellValue('F18', $arrDataBD['typeStransportStart']);
                            if($arrDataBD['typeStransportStart'] == 8)
                            {
                                $start = '00:15';
                            }
                            elseif($arrDataBD['typeStransportStart'] == 2)
                            {
                                $start = '00:05';
                            }
                            $objPHPExcel->getActiveSheet()->setCellValue('B18', $start);
                            $tempTime = $this->hmsToSecond($arrDataBD['timeStart'])+$this->hmsToSecond($start);
                            //$endTime = $this->hmsToSecond($arrDataBD['timechange'])+$tempTime;
                            $endTime = $this->hmsToSecond($timeLuganskCOPP)+$tempTime;
                            $endTime = $this->secondToHMS($endTime);
                            $tempTime = $this->secondToHMS($tempTime);
                            $objPHPExcel->getActiveSheet()->setCellValue('C18', $tempTime);
                            //$objPHPExcel->getActiveSheet()->setCellValue('D18', $arrDataBD['timechange']);
                            //$route[0]['timeSharingLocal'] время стоянки на Луганск ЦОП всегда первый - поэтому ноль
                            $objPHPExcel->getActiveSheet()->setCellValue('D18', $timeLuganskCOPP);
                            $objPHPExcel->getActiveSheet()->setCellValue('E18', $endTime);
                            $objPHPExcel->getActiveSheet()->setCellValue('G18', 'Луганск Центральная касса');
                            //учитываем 5 или 15 минут, между Луганск ЦОПП и Луганской Центральной Кассой
                            $total['time'] += $this->hmsToSecond($start);

views/formationroute/add.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
$this->title = "Добавление данных";
//$this->params['breadcrumbs'][] = $this->title;
use \app\assets\AppAdd;
AppAdd::register($this);
?>
<h2>Добавление или изменение данных</h2>
<input type="hidden" name="url" value="<?=Url::toRoute('addpochta');?>"/>
<img src="../img/285.gif" id="loading-indicator" />
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse1"><span class="glyphicon glyphicon-plus pd-rg"></span> Добавить почтовое отделение</a>
            </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse in">
            <div class="panel-body">
                <?=Html::beginForm(['formationroute/add'],'post',['id'=>'addpochta'])?>
                <div class="form-group">
                    <label for="numberpochta">Номер центра:</label>
                    <select class="form-control" id="numberpochta">
                        <option value="-1">Выберите номер центр</option>
                        <option value="0">0 (Луганск)</option>
                        <option value="1">1 (Алчевск)</option>
                        <option value="2">2 (Первомайск)</option>
                        <option value="3">3 (Антрацит)</option>
                        <option value="4">4 (Краснодон)</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="namepochtaid" class="label-width">Название почтового отделения:</label>
                    <?=Html::input('text','namepochta','',['id' =>'namepochtaid', 'class' =>'form-control','required'=>'']);?>
                </div>
                <div class="form-group">
                    <label for="adresid" class="label-width">Адрес почтового отделения:</label>
                    <?=Html::input('text','adress','',['id' =>'adresid','class' =>'form-control'])?>
                </div>
                <?php echo Html::button('Добавить',['id'=>'addpocthacenter','class'=>'btn btn-default','data-url'=>Url::toRoute('addpochta')])?>
                <?=Html::endForm();?>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse2"><span class="glyphicon glyphicon-random pd-rg"></span>  Добавить данные в матрицу расстояний</a>
            </h4>
        </div>
        <div id="collapse2" class="panel-collapse collapse">
            <div class="panel-body">
                <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                                <div class="form-group">
                                    <select class="form-control" id="matrx-numberpochta">
                                        <option value="-1">Выберите номер центр</option>
                                        <option value="0">0 (Луганск)</option>
                                        <option value="1">1 (Алчевск)</option>
                                        <option value="2">2 (Первомайск)</option>
                                        <option value="3">3 (Антрацит)</option>
                                        <option value="4">4 (Краснодон)</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                    <div class="form-group ">
                                        <input type="text" class="form-control" id="matrx-pochta" placeholder="Введите название почтового отделения:">
                                    </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
                                <?php echo Html::button('<span class="glyphicon glyphicon-cloud-download"></span> Получить ключ',['id'=>'matrx-getkey','class'=>'btn btn-default btn-block','data-url'=>Url::toRoute('addpochta')])?>
                            </div>
                        </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <form class="matrx-form" role="form">
                            <div class="form-group">
                                    <div id="matrx-form"></div>
                            </div>
                            <?php echo Html::button('<span class="glyphicon glyphicon-cloud-upload"> Добавить</span>',['id'=>'matrx-addroute','class'=>'btn btn-default','data-url'=>Url::toRoute('addpochta')])?>
                        </form>
                    </div>
                    </div>
                </div>

            </div>
        </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title attentionDel">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse3"><span class="glyphicon glyphicon-alert pd-rg"></span>  Удалить почтовое отделение</a>
            </h4>
        </div>
        <div id="collapse3" class="panel-collapse collapse">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                        <div class="form-group">
                            <select class="form-control" id="matrx-numberfordel">
                                <option value="-1">Выберите номер центр</option>
                                <option value="0">0 (Луганск)</option>
                                <option value="1">1 (Алчевск)</option>
                                <option value="2">2 (Первомайск)</option>
                                <option value="3">3 (Антрацит)</option>
                                <option value="4">4 (Краснодон)</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                        <?php echo Html::button('<span class="glyphicon glyphicon-th"></span> Показать все отделения для выбранного центра',['id' =>'matrx-seefordel','class'=>'btn btn-default btn-block','data-info'=>'','data-url'=>Url::toRoute('addpochta')])?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <form class="matrx-formDel" role="form">
                            <div class="row">
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>№</th>
                                        <th>Почтовый центр</th>
                                        <th>Название почтового отделения</th>
                                        <th><span class="glyphicon glyphicon-wrench"></span></th>
                                    </tr>
                                    </thead>
                                    <tbody id="matrx-formDel"></tbody>
                                    </table>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title attentionDel">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse4"><span class="glyphicon glyphicon-eye-open pd-rg"></span> Изменить расстояния в матрице  расстояний</a>
            </h4>
        </div>
        <div id="collapse4" class="panel-collapse collapse">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                        <div class="form-group">
                            <select class="form-control" id="matrx-forChange">
                                <option value="-1">Выберите номер центр</option>
                                <option value="0">0 (Луганск)</option>
                                <option value="1">1 (Алчевск)</option>
                                <option value="2">2 (Первомайск)</option>
                                <option value="3">3 (Антрацит)</option>
                                <option value="4">4 (Краснодон)</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                        <?php echo Html::button('<span class="glyphicon glyphicon-th"></span> Показать матрицу расстояний для выбранного центра',['id'=>'matrx-seeforChange','class'=>'btn btn-default btn-block','data-url'=>Url::toRoute('addpochta')])?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <form class="matrx-formChange" role="form">
                            <div class="well"><h4>Расстояния между почтовыми отделениями</h4></div>
                            <div class="row row-eq-height" id="matrx-seeChange"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

views/formationroute/choose.php
<?php
use yii\helpers\Html;
$this->title = "Формирование маршрута";
//$this->params['breadcrumbs'][] = $this->title;

?>
<h2>Формирование маршрута</h2>
<?= Html::beginForm(['formationroute/create', ], 'post') ?>
        <div class="form-group">
        <label for="data">Дата</label>
        <input id="data" type="date" name="dataroute" value="<?php echo date("Y-m-d");?>" required/>
        <p class="help-block">Введите дату выполнения маршрута</p>
        </div>
        <div class="form-group">
            <?php foreach($postoffices as $key=>$post): ?>
                <div class="radio">
                        <?php
                        if($key == 2):
                            echo Html::radio('optradio',true, ['label'=>$post['nameoffices'],'id'=>$post['idcenter'],'value'=>$post['nameoffices'].'|'.$post['idcenter']]);
                        else:
                            echo Html::radio('optradio',false, ['label'=>$post['nameoffices'],'id'=>$post['idcenter'],'value'=>$post['nameoffices'].'|'.$post['idcenter']]);
                        endif;
                        ?>
                </div>
            <?php endforeach;?>
        </div>
    <?= Html::submitButton('Выбрать', ['class' => 'submit']) ?>
<?= Html::endForm() ?>

views/formationroute/create.php
<?php
use yii\helpers\Html;
use \app\assets\AppCreate;
use yii\helpers\Url;
AppCreate::register($this);
?>
<img src="../img/285.gif" id="loading-indicator">
<h2 id="topic-route" data-idcenter="<?=$postoffices['id'];?>" data-tdate="<?=$postoffices['dataroute'];?>">Маршрут <small>на <?=date("d-m-Y",strtotime($postoffices['dataroute']));?></small></h2>
<?= Html::beginForm(['formationroute/create'], 'post', ['id' => 'mainform' ]) ?>
<ul class="list-group">
    <li class="list-group-item">
        <div class="row transport">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h4>Вид транспорта</h4>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
        <label class="radio-inline">
            <input  type="radio" value="8|10" name="typestransport" required>Ведомственный транспорт
        </label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-8 col-lg-10">
        <label class="radio-inline">
            <input type="radio" value="2|2" name="typestransport">Наемный транспорт
        </label>
        </div>
    </div>
    </li>
    <li class="list-group-item">
        <div class="row">
            <?php foreach ($postcenters as $office): ?>
                       <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 checkbox amendment">
                              <div class="row">
                                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="height: 35px;">
                                      <?=Html::checkbox('pochta',false, ['label'=>$office->namepochta,'id' => $office->idcenterspost,'class' =>"pochta-input",'data-adress' => $office->adress]);?>
                                      <?=Html::tag('p','',['id'=>'choicepochta'.$office->idcenterspost]) ;?>
                                  </div>
                              </div>
                           <div class="row">
                               <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <small><i><?=$office->adress;?></i></small>
                               </div>
                           </div>
                           <div class="row">
                               <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <?= Html::input('time', 'timesharing', '00:05', ['id' =>'time-sharing'.$office->idcenterspost]) ?>
                               </div>
                           </div>
                           <div class="row">
                               <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                   <span for="time-sharing<?=$office->idcenterspost;?>">Время обмена</span>
                               </div>
                           </div>
                       </div>
            <?php endforeach ;?>
    </div>
    </li>
    <li class="list-group-item">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 timetransport">
                <input type="time"  id="time-departure" value="05:55"  name="timedeparture">
                <label for="time-departure">Время выезда из гаража</label>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 timetransport">
               <!-- <input type="time"  id="time-sharing" value="00:10" name="timesharing">
                <label for="time-sharing">Время обмена</label> -->
                <input type="text"  id="route-name" name="routename" value="<?=$postoffices['nameoffices'];?>" placeholder="Название маршрута">
                <label for="route-name">Название маршрута</label>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 timetransport">
                <input type="time"  id="duration-break" name="durationbreak" value="00:20">
                <label for="duration-break">Продолжительность перерыва</label>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 timetransport">
                <div class="btn-group">
                    <select class="form-control" name="placebreak" id="place-break" style="max-width: 190px">
                        <option value="-1">Место перерыва</option>
                    </select>
                </div>
                <span class="placebreak placebreak-hide">Место перерыва</span>
            </div>

        </div>
        <div class="row">
            <div class="col-xs-10 col-sm-10 col-md-11 col-lg-11 timetransport settling">
                <input type="time"  class="settling-time" name="durationbreak" value="00:00">
                <label for="settling-time">Время отстоя</label>
                <div class="btn-group">
                    <select class="form-control place-settling" name="placesettling" style="max-width: 190px">
                        <option value="-1">Место отстоя</option>
                    </select>
                </div>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-1 col-lg-1 timetransport">
                <button id="settling-btn" type="button" class="btn btn-default btn-sm" >
                    <span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="Добавить поле для времени отстоя!"></span>
                </button>
            </div>
        </div>
    </li>
</ul>
    <?= Html::Button('Создать маршрут', ['id' =>'create-route','class' => 'btn btn-default submit']) ?>
    <?= Html::Button('Добавить новый маршрут', ['id' =>'add-new-route', 'class' => 'btn btn-primary btn-disable',]) ?>
    <?= Html::submitButton('Сформировать расписание', ['id' =>'shape-schedule', 'class' => 'btn btn-primary btn-disable','data-url'=>Url::toRoute('createxsel')]) ?>
<?= Html::endForm();?>

<div class="alert alert-info" style="margin-top: 20px;"></div>

views/formationroute/help.php
<?php
use yii\helpers\Html;
use \app\assets\AppCreate;
AppCreate::register($this);
?>
<div class="body-content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h2>Формирование маршрута</h2>
            <ol>
                <li>Для формирования маршрута перейдите на страницу формирования маршрута</li>
                <li>В поле 'дата' введите дату на которую нужно сформировать накладную (при запуске программа выводит текущую дату)</li>
                <li>Выберите почтовый центр, нажав на поле возле соответствующего центра (Луганск, Алчевск, Первомайск, Антрацит, Краснодон)</li>
                <li>Нажмите на кнопку 'Выбрать', после чего произойдет переход на следующую страницу формирования маршрута</li>
                <li>На страинице 'Маршрут' отобразяться все почтовые отделения, выберите в порядке следования почтовые отделения, выберите вид транспрота и место перерыва.</li>
                <li>После этого нажмите на кнопку 'Создать маршрут'</li>
                <li>Затем отобразиться предпросмотор выбранного маршрута (ниже кнопки 'Создать маршрут') и станут активными кнопки 'Добавить новый маршрут', 'Сформировать расписание'.</li>
                <li>Если нужно добавить новый маршрут для данного почтового центра
                    <ol>
                        <li> Нажмите кнопку 'Добавить новый машрут' - и повторите последовательность действий из 5 и 6 пункта.</li>
                        <li>Если же нужно получить сформированную накладную в виде Excel файла нажмите кнопку 'Сформировать расписание', после генерации файла, его можно загрузить на свой компьютер - нажав на кнопку 'Скачать файл'.</li>
                    </ol>
                </li>
            </ol>
        </div>
    </div>

</div>